abstract class StatesRegister{}
class StateInitiaRegister extends StatesRegister{}
class StateChangeVisibileterRegisterPassword extends StatesRegister{}
class StateChangeVisibileterRegisterConfiPassword extends StatesRegister{}